const express=require('express');
const router=express.Router();
const admin_controller=require('../controllers/admin_controller');
const { require_auth } = require('../middleware/auth_middlware');
const is_admin = require('../middleware/role_middleware');
router.get('/admin',require_auth,is_admin,admin_controller.admin);
router.get('/admin/:id',require_auth,is_admin,admin_controller.admin_id);
router.get('/admin/:id/edit',require_auth,is_admin,admin_controller.edit_get);
router.post('/admin/:id/edit',require_auth,is_admin,admin_controller.edit_post);
router.post('/admin/:id/delete',require_auth,is_admin,admin_controller.delete);
module.exports=router;